<!--
///////////////////////////////////////////////////////////////////////////////
// Product        :  Online Tools(tm)
//
// Series         :  Dovetail Software Development Series(tm)
//
// Name           :  footer.inc
//
// Description    :  Shared page footer
//
// Author         :  Dovetail Software, Inc.
//                   4807 Spicewood Springs Rd, Bldg 4 Suite 200
//                   Austin, TX 78759
//                   (512) 610-5400
//                   EMAIL: support@dovetailsoftware.com
//                   www.dovetailsoftware.com
//
// Platforms      :  This version supports Clarify 9.0 and later
//
// Copyright (C) 2001-2012 Dovetail Software, Inc.
// All Rights Reserved.
///////////////////////////////////////////////////////////////////////////////
-->
<footer>
	<div id="boltFooter" class="row bt-2">
		<div class="col-8 offset-2 card bg-faded">
			<h2>Support</h2>
   		<p>For support, contact us at <a href=http://support.dovetailsoftware.com>support.dovetailsoftware.com</a>.</p>
		</div>
	</div>
</footer>


	