<div id="help" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header no-border-bottom">
	  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
	  <h3 id="myModalLabel">Keyboard shortcuts</h3>
	</div>
	<div class="modal-body">
		<table class="help table table-condensed table-striped">
			<tr>
				<td class="shortcut">alt-s</td>
				<td>Execute SQL</td>
			</tr>
			<tr class="object hide">
				<td class="shortcut">alt-t</td>
				<td>Execute SQL, getting latest 10 rows</td>
			</tr>
			<tr class="sql hide">
				<td class="shortcut">alt-x</td>
				<td>Swap SQL and Clipboard</td>
			</tr>
			<tr>
				<td class="shortcut">?</td>
				<td>Bring up this help dialog</td>
			</tr>
		</table>
	</div>
</div>
