<div id="help" class="modal" tabindex="-1" role="dialog" aria-labelledby="helpModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
			  <h5 class="modal-title" id="helpModalLabel">Keyboard shortcuts</h5>
			  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		      <span aria-hidden="true">&times;</span>
		    </button>
			</div>
			<div class="modal-body">
				<table class="table table-sm table-striped">
					<tr>
						<td>alt-s</td>
						<td>Execute SQL</td>
					</tr>
					<tr class="object hidden-xs-up">
						<td>alt-t</td>
						<td>Execute SQL, getting latest 10 rows</td>
					</tr>
					<tr>
						<td>?</td>
						<td>Bring up this help dialog</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>
