<!--
///////////////////////////////////////////////////////////////////////////////
// Product				:	Online Tools(tm)
//
// Series				 :	Dovetail Software Development Series(tm)
//
// Name					 :	navbar.inc
//
// Description		:	Shared menu bar
//
// Author				 :	Dovetail Software, Inc.
//									 4807 Spicewood Springs Rd, Bldg 4 Suite 200
//									 Austin, TX 78759
//									 (512) 610-5400
//									 EMAIL: support@dovetailsoftware.com
//									 www.dovetailsoftware.com
//
// Platforms			:	This version supports Clarify 9.0 and later
//
// Copyright (C) 2001-2012 Dovetail Software, Inc.
// All Rights Reserved.
///////////////////////////////////////////////////////////////////////////////
-->
<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class=""><a href="index.asp">Schema</a></li>
					<li class=""><a href="formsonline.asp">Forms</a></li>
					<li class=""><a href="bizrules.asp">Rules</a></li>
					<li class=""><a href="dbInfo.asp">Database</a></li>
					<li class=""><a href="sql.asp">SQL</a></li>
					<li class=""><a href="lists.asp">Lists</a></li>
					<li class=""><a href="licenses.asp">Licenses</a></li>
					<li class=""><a href="about.asp">About</a></li>
					<li class=""><a class="connected" href="admin.asp" title="Change Connection"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
