<%
///////////////////////////////////////////////////////////////////////////////
// Product        :  Online Tools(tm)
//
// Series         :  Dovetail Software Development Series(tm)
//
// Name           :  quicklinks.inc
//
// Description    :  Tables/Views to be displayed as quicklinks
//
// Author         :  Dovetail Software, Inc.
//                   4807 Spicewood Springs Rd, Bldg 4 Suite 200
//                   Austin, TX 78759
//                   (512) 610-5400
//                   EMAIL: support@dovetailsoftware.com
//                   www.dovetailsoftware.com
//
// Platforms      :  This version supports Clarify 9.0 and later
//
// Copyright (C) 2001-2012 Dovetail Software, Inc.
// All Rights Reserved.
///////////////////////////////////////////////////////////////////////////////

var LinkIndex = 1;
var LinkArray = [];

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "act_entry";
LinkArray[LinkIndex++][2]= "21";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "case";
LinkArray[LinkIndex++][2]= "0";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "contact";
LinkArray[LinkIndex++][2]= "45";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "employee";
LinkArray[LinkIndex++][2]= "44";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "rol_contct";
LinkArray[LinkIndex++][2]= "289";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "site";
LinkArray[LinkIndex++][2]= "52";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "site_view";
LinkArray[LinkIndex++][2]= "88";

LinkArray[LinkIndex] = [];
LinkArray[LinkIndex][1]= "user";
LinkArray[LinkIndex++][2]= "20";

%>
