<%
///////////////////////////////////////////////////////////////////////////////
// Product        :  Online Tools(tm)
//
// Series         :  Dovetail Software Development Series(tm)
//
// Name           :  quicklinks.inc
//
// Description    :  Tables/Views to be displayed as quicklinks
//
// Author         :  Dovetail Software, Inc.
//                   4807 Spicewood Springs Rd, Bldg 4 Suite 200
//                   Austin, TX 78759
//                   (512) 610-5400
//                   EMAIL: support@dovetailsoftware.com
//                   www.dovetailsoftware.com
//
// Platforms      :  This version supports Clarify 9.0 and later
//
// Copyright (C) 2001-2012 Dovetail Software, Inc.
// All Rights Reserved.
///////////////////////////////////////////////////////////////////////////////

var LinkIndex = 1;
var LinkArray = [];

LinkArray[LinkIndex++] = ["", "act_entry", "21"];
LinkArray[LinkIndex++] = ["", "case", "0"];
LinkArray[LinkIndex++] = ["", "contact", "45"];
LinkArray[LinkIndex++] = ["", "employee", "44"];
LinkArray[LinkIndex++] = ["", "rol_contct", "289"];
LinkArray[LinkIndex++] = ["", "site", "52"];
LinkArray[LinkIndex++] = ["", "site_view", "88"];
LinkArray[LinkIndex++] = ["", "user", "20"];

%>
